{
 "title": "UR3e Robot Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running Status",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ur3e\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"robotarm.pt.state\")\n  |> filter(fn: (r) => r[\"_field\"] == \"robot_mode\")\n  |> last()\n  |> map(fn: (r) => ({ _value: string(v: r._value) }))"
    }
   ]
  },
  {
   "title": "Active Program",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ur3e\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"robotarm.ctrl\")\n  |> filter(fn: (r) => r[\"_field\"] == \"type\")\n  |> last()\n  |> map(fn: (r) => ({ _value: string(v: r._value) }))"
    }
   ]
  },
  {
   "title": "Stuck Joint Status",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ur3e\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stuck_joint.status\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /stuck_joints_.*/)\n  |> last()\n  |> map(fn: (r) => ({ _value: string(v: r._value) }))"
    }
   ]
  },
  {
   "title": "Max Acceleration and Speed",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 8, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ur3e\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rt_model.dt.state\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /joint_max_acceleration_.*/ or r[\"_field\"] =~ /joint_max_speed_.*/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Q_actual & Q_target",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 4, "w": 8, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ur3e\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rt_model.dt.state\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /q_actual_.*/ or r[\"_field\"] =~ /q_target_.*/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "TCP Position",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 4, "w": 8, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ur3e\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"robotarm.pt.state\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /tcp_pose_.*/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}