FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential gcc g++ python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY pyproject.toml poetry.lock* ./
COPY communication/ communication/
COPY DTsolution/utils utils

RUN poetry config virtualenvs.create false \
    && poetry install --no-root