x-base-build: &base-build
  context: .
  dockerfile: Dockerfile.base
  target: service

services:
  influxdb:
    container_name: influxdb-server
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ur3e
      DOCKER_INFLUXDB_INIT_PASSWORD: ur3eur3e
      DOCKER_INFLUXDB_INIT_ORG: ur3e
      DOCKER_INFLUXDB_INIT_BUCKET: ur3e
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: SECRET_AF
    volumes:
      - db-data:/var/lib/influxdb:rw
    ports:
      - 8086:8086

  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:3.12-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ur3e
      RABBITMQ_DEFAULT_PASS: ur3e
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_federation_management rabbitmq_stomp &&
            docker-entrypoint.sh rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 15s

  mockup:
    container_name: ur3e_mockup
    build:
      context: ./ur3e_mockup
      dockerfile: ${DOCKERFILE:-Dockerfile.x86}
    volumes:
      - ./startup/startup.conf:/app/startup.conf:z
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy

  data_recorder:
    container_name: data_recorder
    build: 
      <<: *base-build
    volumes:
      - ./communication/connect.yml:/app/connect.yml:rw
      - ./DTsolution/DTservices/data_recorder/influxdb.yml:/app/influxdb.yml:rw
      - ./DTsolution/DTservices/data_recorder/data_recorder.py:/app/data_recorder.py
    command: python -u data_recorder.py
    depends_on:
      - influxdb
      - mockup

  abnormal_movement:
    container_name: abnormal_movement
    build: 
      <<: *base-build
    volumes:
      - ./communication/connect.yml:/app/connect.yml:rw
      - ./DTsolution/DTservices/abnormal_movement/abnormal_movement.py:/app/abnormal_movement.py
    command: python -u abnormal_movement.py
    depends_on:
      - mockup

  stuck_joint:
    container_name: stuck_joint
    build: 
      <<: *base-build
    volumes:
      - ./communication/connect.yml:/app/connect.yml:rw
      - ./DTsolution/DTservices/stuck_joint_detection/stuck_joint.py:/app/stuck_joint.py
    command: python -u stuck_joint.py
    depends_on:
      - mockup

  rt_robot_prediction:
    container_name: robot_prediction
    build: 
      <<: *base-build
    volumes:
      - ./communication/connect.yml:/app/connect.yml:rw
      - ./DTsolution/models:/app/DTsolution/models
      - ./DTsolution/DTservices/RT_robot_prediction/prediction.py:/app/prediction.py
    command: python -u prediction.py
    depends_on:
      - mockup

  robot_ctrl:
    container_name: robot_ctrl
    build: 
      <<: *base-build
    volumes:
      - ./communication/connect.yml:/app/connect.yml:rw
      - ./DTsolution/scripts/robot_ctrl.py:/app/robot_ctrl.py
    command: python -u robot_ctrl.py
    depends_on:
      - mockup
  grafana:
    container_name: grafana-visualizer
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=ur3e
      - GF_SECURITY_ADMIN_PASSWORD=ur3epassword
    volumes:
      - grafana-data:/var/lib/grafana:rw
      - ./DTsolution/DTservices/Grafana/Dashboards:/var/lib/grafana/dashboards
      - ./DTsolution/DTservices/Grafana/Dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./DTsolution/DTservices/Grafana/Datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - influxdb
      - rt_robot_prediction
  godot:
    container_name: godot
    build: 
      context: .
      dockerfile: ${DOCKERFILE2:-DTsolution/DTservices/GODOT_Visualization_service/ur-3e-visualization/Dockerfile.x86}
    volumes:
      - ./communication/connect.yml:/app/connect.yml:rw
    ports:
      - "6080:6080"
    depends_on:
      - mockup
  inv_kinematics:
    container_name: inv_kinematics
    build:
      <<: *base-build
    volumes:
      - ./communication/connect.yml:/app/connect.yml:rw
      - ./DTsolution/DTservices/inv_kinematics/inv_kinematics.py:/app/inv_kinematics.py
    command: python -u inv_kinematics.py
    depends_on:
      - stuck_joint
volumes:
  db-data:
  grafana-data: